export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const SHOW_NAVIGATION = 'SHOW_NAVIGATION';

export const SAVE_SUCCESS_EVENT_RESPONSE_TO_STATE =
  'SAVE_SUCCESS_EVENT_RESPONSE_TO_STATE';

export const SHOW_HEALTH_EVENT_LOADING = 'SHOW_HEALTH_EVENT_LOADING';
export const ERROR_IN_HEALTH_EVENT_API = 'ERROR_IN_HEALTH_EVENT_API';
