export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const SHOW_NAVIGATION = 'SHOW_NAVIGATION';

export const SAVE_SUCCESS_EVENT_RESPONSE_TO_STATE =
  'SAVE_SUCCESS_EVENT_RESPONSE_TO_STATE';
export const SHOW_HEALTH_EVENT_LOADING = 'SHOW_HEALTH_EVENT_LOADING';
export const ERROR_IN_HEALTH_EVENT_API = 'ERROR_IN_HEALTH_EVENT_API';

export const ADD_MEETING_EVENT_REQUEST = 'ADD_MEETING_EVENT_REQUEST';
export const ADD_MEETING_EVENT_SUCCESS = 'ADD_MEETING_EVENT_SUCCESS';
export const ADD_MEETING_EVENT_FAILURE = 'ADD_MEETING_EVENT_FAILURE';

export const NEW_VERSION_AVAILABLE = 'NEW_VERSION_AVAILABLE';
